name: fitness_booking
description: Fitness Booking App
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

  http: ^1.6.0
  csv: ^6.0.0

  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  cached_network_image: ^3.4.1

  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_stripe: ^11.1.0
  pdf: ^3.11.1
  cloud_functions: ^6.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_adaptive_fg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
