// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xiDPvQ9mb_CFRtwlzwMHh3g_pgjDD0o',
    appId: '1:100021036305:web:e4f9d3a3509a31cf1298b0',
    messagingSenderId: '100021036305',
    projectId: 'fitness-booking-app-23bdc',
    authDomain: 'fitness-booking-app-23bdc.firebaseapp.com',
    storageBucket: 'fitness-booking-app-23bdc.firebasestorage.app',
    measurementId: 'G-L7N9CRZQHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvkxnGTAqRLOUteLEtMdFZ1x1Uj0aXKU',
    appId: '1:100021036305:android:f1eb4a0f7afe91fd1298b0',
    messagingSenderId: '100021036305',
    projectId: 'fitness-booking-app-23bdc',
    storageBucket: 'fitness-booking-app-23bdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXsX_R2cEVQ1Rfo5t6LZ2p_M_p82D5Nc',
    appId: '1:100021036305:ios:d99f7bf0e0265f151298b0',
    messagingSenderId: '100021036305',
    projectId: 'fitness-booking-app-23bdc',
    storageBucket: 'fitness-booking-app-23bdc.firebasestorage.app',
    iosClientId: '100021036305-mjnvnpt3m9b6a00ouf9cmb1fi5vuhk9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXsX_R2cEVQ1Rfo5t6LZ2p_M_p82D5Nc',
    appId: '1:100021036305:ios:d99f7bf0e0265f151298b0',
    messagingSenderId: '100021036305',
    projectId: 'fitness-booking-app-23bdc',
    storageBucket: 'fitness-booking-app-23bdc.firebasestorage.app',
    iosClientId: '100021036305-mjnvnpt3m9b6a00ouf9cmb1fi5vuhk9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0xiDPvQ9mb_CFRtwlzwMHh3g_pgjDD0o',
    appId: '1:100021036305:web:5dbde833ebd394ee1298b0',
    messagingSenderId: '100021036305',
    projectId: 'fitness-booking-app-23bdc',
    authDomain: 'fitness-booking-app-23bdc.firebaseapp.com',
    storageBucket: 'fitness-booking-app-23bdc.firebasestorage.app',
    measurementId: 'G-0B63XG2NM1',
  );
}
